// User
export const USER_NAME = 'USER_NAME'
export const USER_ID = 'USER_ID'
export const USER_RIDE_HISTORY = 'USER_RIDE_HISTORY'
export const USER_SCHEDULED_RIDE = 'USER_SCHEDULED_RIDE'
export const USER_PHONE_NUMBER = 'USER_PHONE_NUMBER'
export const USER_PASSWORD = 'USER_PASSWORD'
export const USER_KHIZAR_CREDIT = 'USER_KHIZAR_CREDIT'
export const USER_CURRENT_PICKUP = 'USER_CURRENT_PICKUP'
export const USER_CURRENT_DROPOFF = 'USER_CURRENT_DROPOFF'

// login
export const SIGNIN_REQUEST = 'LOGIN_REQUEST';
export const SIGNIN_RESPONSE = 'LOGIN_RESPONSE';
export const SIGNIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const SIGNIN_FAILED = 'LOGIN_FAILED';
export const SIGNIN_CHANGE_STATE = 'LOGIN_CHANGE_STATE';

//forgot password
export const FORGOT_REQUEST = 'FORGOT_REQUEST';
export const FORGOT_RESPONSE = 'FORGOT_RESPONSE';
export const FORGOT_FAILED = 'FORGOT_FAILED';
export const FORGOT_LOADING_ENDED = 'FORGOT_LOADING_ENDED';
export const FORGOT_CHANGE_STATE = 'FORGOT_CHANGE_STATE';

//reset password
export const RESET_REQUEST = 'RESET_REQUEST';
export const RESET_RESPONSE = 'RESET_RESPONSE';
export const RESET_FAILED = 'RESET_FAILED';
export const RESET_LOADING_ENDED = 'RESET_LOADING_ENDED';
export const RESET_CHANGE_STATE = 'RESET_CHANGE_STATE';